Repository flyimg/flyimg, pull requests merged in 2019-08, with the labels that each got.

#212 Instructions to replace default parameters file
  README.md
Labels: Docs, enhancement, version 1

#214 Fix composer install warning, closes #213
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Core/Processor/ImageProcessor.php
  tests/Core/BaseTest.php
  tests/Core/Entity/AppParametersTest.php
  tests/Core/Processor/ProcessorTest.php
Labels: UnitTest, enhancement, version 1

#216 Update php minimum version to 7.1, closes #215
  composer.json
  composer.lock
Labels: enhancement, version 1

#218 Update docker libraries and move to use tags images, closes #217
  Dockerfile
  composer.json
  tests/Core/BaseTest.php
  tests/Core/Entity/Image/InputImageTest.php
  tests/Core/Entity/Image/OutputImageTest.php
  tests/Core/Entity/ImageMetaInfoTest.php
  tests/Core/Handler/ImageHandlerTest.php
  tests/Core/Handler/SecurityHandlerTest.php
  tests/Core/Processor/ExtractProcessorTest.php
  tests/Core/Processor/FaceDetectProcessorTest.php
  tests/Core/Processor/ImageProcessorTest.php
  tests/Core/Processor/ProcessorTest.php
  tests/Core/Resolver/ControllerResolver.php
  tests/Core/StorageProvider/S3StorageProviderTest.php
  tests/testImages/extract-result.jpg
  tests/testImages/face_cp0.jpg
  tests/testImages/face_fb.jpg
Labels: UnitTest, enhancement, version 1

#220 Update CHANGELOG.md, closes #219
  CHANGELOG.md
Labels: Docs, enhancement, version 1

#222 Refactor ExtractProcessor class, closes #221
  src/Core/Handler/ImageHandler.php
  src/Core/Processor/ExtractProcessor.php
Labels: enhancement, version 1

#224 Add Cloud Run Button to Flyimg
  Dockerfile
  README.md
  tests/Core/Entity/ImageMetaInfoTest.php
  tests/testImages/extract-result.jpg
  tests/testImages/face_cp0.jpg
  tests/testImages/face_fb.jpg
Labels: enhancement, version 1
