Repository flyimg/flyimg, pull requests merged in 2024-05, with the labels that each got.

#442 Fixing UnitTests Deprecations warnings, closes #441
  tests/Core/Entity/Image/InputImageTest.php
  tests/Core/Entity/Image/OutputImageTest.php
  tests/Core/Entity/ImageMetaInfoTest.php
  tests/Core/Processor/ImageProcessorTest.php
Labels: enhancement, UnitTest

#443 fix: update flyimg base version to support multi arch build, fixing #414
  Dockerfile
Labels: enhancement, version 1

#445 fix: Rename the build image to flyimg/flyimg, run composer update, closes #444
  .github/workflows/cd.yml
  README.md
  composer.lock
  tests/testImages/face_cp0.png
Labels: enhancement, version 1

#447 chore: add Star History image
  README.md
Labels: enhancement, version 1

#451 fix: add options_separator to js code
  config/parameters.yml
  docs/application-options.md
  web/js/main.js
Labels: bug, enhancement, version 1

#455 fix: fix default separator in js code
  web/js/main.js
Labels: bug, enhancement, version 1

#456 Additional S3 parameters.
  docs/application-options.md
  src/Core/StorageProvider/S3StorageProvider.php
Labels: enhancement, version 1
