Repository flyimg/flyimg, pull requests merged in 2024-11, with the labels that each got.

#542 Extended exceptions logic
  .github/dependabot.yml
  .github/workflows/branch-dev-deploy.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/close_inactive_issues.yml
  .github/workflows/docs.yml
  composer.json
  composer.lock
  config/parameters.yml
  config/routes.yml
  mkdocs.yml
  phpunit.xml.dist
  src/Core/Entity/Image/InputImage.php
  src/Core/Exception/AccessDeniedException.php
  src/Core/Exception/AppException.php
  src/Core/Exception/ExecFailedException.php
  src/Core/Exception/FileNotFoundException.php
  src/Core/Exception/InvalidArgumentException.php
  src/Core/Exception/MissingParamsException.php
  src/Core/Exception/ReadFileException.php
  src/Core/Exception/SecurityException.php
  src/Core/Exception/ServiceUnavailableException.php
  src/Core/Exception/UnauthorizedException.php
  tests/Core/Exception/AccessDeniedExceptionTest.php
  tests/Core/Exception/AppExceptionTest.php
  tests/Core/Exception/ExceptionBaseTest.php
  tests/Core/Exception/FileNotFoundExceptionTest.php
  tests/Core/Exception/InvalidArgumentExceptionTest.php
  tests/Core/Exception/ServiceUnavailableExceptionTest.php
  tests/Core/Exception/UnauthorizedExceptionTest.php
  tests/Core/Processor/ImageProcessorTest.php
  tests/MockResponseCodeServer.php
Labels: enhancement, version 1, UnitTest

#544 fix: fix Github workflow, closes #543
  .github/workflows/branch-dev-deploy.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: bug

#545 fix: refactor python to remove unused code
  python/facedetect.py
  python/smartcrop.py
Labels: enhancement
